# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 13:40
from __future__ import unicode_literals

from django.db import migrations


def add_group_permissions(apps, schema_set):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='mi_group')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginfailure'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
