# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-22 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=128)),
            ],
        ),
    ]
