# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-22 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0002_sectorteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorteam',
            old_name='team_name',
            new_name='name',
        ),
    ]
