# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0009_auto_20161130_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, unique=True)),
                ('overseas_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='mi.OverseasRegion')),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='sector_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.SectorTeam'),
        ),
    ]
