# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 15:40
from __future__ import unicode_literals

from django.db import migrations

def do_thing(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0012_target_country'),
    ]

    operations = [
        migrations.RunPython(do_thing),
    ]
