# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_parent_sectors(apps, schema_editor):
    ParentSector = apps.get_model('mi', 'ParentSector')
    SectorTeam = apps.get_model('mi', 'SectorTeam')

    parent_sectors = {1: 'Advanced Engineering', 2: 'Advanced Manufacturing', 3: 'Aerospace', 4: 'Agriculture, Horticulture and Fisheries', 5: 'Agritech', 6: 'Aid Funded Business', 7: 'Airports', 8: 'Automotive', 9: 'Biotechnology and Pharmaceuticals', 10: 'Business (and Consumer) Services', 11: 'Chemicals', 12: 'Clothing, Footwear and Fashion', 13: 'Communications', 14: 'Construction', 15: 'Consumer Goods & Retail', 16: 'Creative and Media', 17: 'Creative Industries', 18: 'Defence', 19: 'Defence and Security', 20: 'Digital Economy', 21: 'Education', 22: 'Education and Training', 23: 'Electronics and IT Hardware', 24: 'Energy', 25: 'Environment', 26: 'Environment and Water', 27: 'Financial Services', 28: 'Financial Services (including Professional Services)', 29: 'Food and Drink', 30: 'Giftware, Jewellery and Tableware', 31: 'Global Sports Projects', 32: 'Healthcare', 33: 'Healthcare and Medical', 34: 'Household Goods, Furniture and Furnishings', 35: 'ICT', 36: 'Leisure and Tourism', 37: 'Life Sciences', 38: 'Marine', 39: 'Mass Transport', 40: 'Mechanical Electrical and Process Engineering', 41: 'Metallurgical Process Plant', 42: 'Metals, Minerals and Materials', 43: 'Mining', 44: 'Nuclear', 45: 'Oil and Gas', 46: 'Ports and Logistics', 47: 'Power', 48: 'Professional Business Services', 49: 'Railways', 50: 'Renewable Energy', 51: 'Retail', 52: 'Security', 53: 'Software and Computer Services Business to Business (B2B)', 54: 'Sports Economy', 55: 'Textiles, Interior Textiles and Carpets', 56: 'Water'}
    parent_sector_to_sector_team = {'Education and Training': 'Education', 'Giftware, Jewellery and Tableware': 'Consumer & Creative', 'Healthcare': 'Healthcare', 'Financial Services (including Professional Services)': 'Financial & Professional Services', 'Sports Economy': 'Consumer & Creative', 'Power': 'Energy', 'Textiles, Interior Textiles and Carpets': 'Consumer & Creative', 'Energy': 'Energy', 'Household Goods, Furniture and Furnishings': 'Consumer & Creative', 'Mass Transport': 'Infrastructure', 'Chemicals': 'Bio-economy', 'Environment and Water': 'Infrastructure', 'Agritech': 'Bio-economy', 'Ports and Logistics': 'Infrastructure', 'Renewable Energy': 'Energy', 'Airports': 'Infrastructure', 'Aerospace': 'Aerospace', 'Leisure and Tourism': 'Consumer & Creative', 'Defence': 'Defence & Security', 'Marine': 'Advanced Manufacturing', 'Financial Services': 'Financial & Professional Services', 'Water': 'Infrastructure', 'Oil and Gas': 'Energy', 'Creative Industries': 'Consumer & Creative', 'Automotive': 'Automotive', 'Agriculture, Horticulture and Fisheries': 'Bio-economy', 'Consumer Goods & Retail': 'Consumer & Creative', 'Food and Drink': 'Food & Drink', 'Clothing, Footwear and Fashion': 'Consumer & Creative', 'Mechanical Electrical and Process Engineering': 'Advanced Manufacturing', 'Mining': 'Infrastructure', 'Retail': 'Consumer & Creative', 'Creative and Media': 'Consumer & Creative', 'Digital Economy': 'Technology', 'Life Sciences': 'Life Sciences', 'Aid Funded Business': 'Infrastructure', 'Advanced Manufacturing': 'Advanced Manufacturing', 'Global Sports Projects': 'Consumer & Creative', 'Environment': 'Infrastructure', 'Biotechnology and Pharmaceuticals': 'Life Sciences', 'Metals, Minerals and Materials': 'Infrastructure', 'Advanced Engineering': 'Advanced Manufacturing', 'Electronics and IT Hardware': 'Technology', 'Metallurgical Process Plant': 'Advanced Manufacturing', 'Nuclear': 'Energy', 'Professional Business Services': 'Financial & Professional Services', 'Business (and Consumer) Services': 'Financial & Professional Services', 'Defence and Security': 'Defence & Security', 'Railways': 'Infrastructure', 'Construction': 'Infrastructure', 'Software and Computer Services Business to Business (B2B)': 'Technology', 'Communications': 'Technology', 'ICT': 'Technology', 'Education': 'Education', 'Security': 'Defence & Security', 'Healthcare and Medical': 'Healthcare'}

    for parent_id, parent_name in parent_sectors.items():
        team = parent_sector_to_sector_team[parent_name]
        sector_team=SectorTeam.objects.get(name=team)
        ParentSector(id=parent_id, name=parent_name, sector_team=sector_team).save()


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0014_auto_20170104_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sector_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_sectors', to='mi.SectorTeam')),
            ],
        ),
        migrations.RunPython(add_parent_sectors),
        migrations.AddField(
            model_name='sector',
            name='parent_sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='mi.ParentSector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='parent_sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.ParentSector'),
            preserve_default=False,
        ),
    ]
