# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-19 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def add_hvc_group(apps, schema_editor):
    HVCGroup = apps.get_model('mi', 'HVCGroup')
    SectorTeam = apps.get_model('mi', 'SectorTeam')

    hvc_group_to_sector_team = {
        "Advanced Manufacturing": "Advanced Manufacturing",
        "Advanced Manufacturing - Marine": "Advanced Manufacturing",
        "Aerospace": "Aerospace",
        "Automotive": "Automotive",
        "Bio-economy - Agritech": "Bio-economy",
        "Bio-economy - Chemicals": "Bio-economy",
        "Consumer Goods & Retail": "Consumer & Creative",
        "Creative Industries": "Consumer & Creative",
        "Defence": "Defence & Security",
        "Digital Economy": "Technology",
        "Education": "Education",
        "Energy - Nuclear": "Energy",
        "Energy - Offshore Wind": "Energy",
        "Energy - Oil & Gas": "Energy",
        "Energy - Renewables": "Energy",
        "Financial Services": "Financial & Professional Services",
        "Food & Drink": "Food & Drink",
        "Healthcare": "Healthcare",
        "Infrastructure - Aid Funded Business": "Infrastructure",
        "Infrastructure - Airports": "Infrastructure",
        "Infrastructure - Construction": "Infrastructure",
        "Infrastructure - Mining": "Infrastructure",
        "Infrastructure - Rail": "Infrastructure",
        "Infrastructure - Water": "Infrastructure",
        "Life Sciences": "Life Sciences",
        "Professional Services": "Financial & Professional Services",
        "Sports Economy": "Consumer & Creative",
        "Strategic Campaigns": "Defence & Security"
    }

    hvc_groups = {
        1: 'Advanced Manufacturing',
        2: 'Advanced Manufacturing - Marine',
        3: 'Aerospace',
        4: 'Automotive',
        5: 'Bio-economy - Agritech',
        6: 'Bio-economy - Chemicals',
        7: 'Consumer Goods & Retail',
        8: 'Creative Industries',
        9: 'Defence',
        10: 'Digital Economy',
        11: 'Education',
        12: 'Energy - Nuclear',
        13: 'Energy - Offshore Wind',
        14: 'Energy - Oil & Gas',
        15: 'Energy - Renewables',
        16: 'Financial Services',
        17: 'Food & Drink',
        18: 'Healthcare',
        19: 'Infrastructure - Aid Funded Business',
        20: 'Infrastructure - Airports',
        21: 'Infrastructure - Construction',
        22: 'Infrastructure - Mining',
        23: 'Infrastructure - Rail',
        24: 'Infrastructure - Water',
        25: 'Life Sciences',
        26: 'Professional Services',
        27: 'Sports Economy',
        28: 'Strategic Campaigns'
    }
    for group_id, group_name in hvc_groups.items():
        team = hvc_group_to_sector_team[group_name]
        sector_team = SectorTeam.objects.get(name=team)
        HVCGroup(id=group_id, name=group_name, sector_team=sector_team).save()


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0017_auto_20170112_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='HvcGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sector_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hvc_groups', to='mi.SectorTeam')),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='parent_sector',
        ),
        migrations.RunPython(add_hvc_group),
        migrations.AddField(
            model_name='target',
            name='hvc_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='mi.HVCGroup'),
            preserve_default=False,
        ),
    ]
