# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-20 12:53
from __future__ import unicode_literals

from django.db import migrations


def clear_sector_parents(apps, schema_editor):
    Sector = apps.get_model('mi', 'Sector')
    sectors = Sector.objects.all()
    for sector in sectors:
        sector.parent_sector = None
        sector.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0020_auto_20170120_1251'),
    ]

    operations = [
        migrations.RunPython(clear_sector_parents),
    ]
