# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-20 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0022_auto_20170120_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='parent_sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='mi.ParentSector'),
            preserve_default=False,
        ),
    ]
