# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-23 14:35
from __future__ import unicode_literals

from django.db import migrations


def correct_targets(apps, schema_editor):
    """
    Targets - HVC Groups mapping was incorrect for Marine, this corrects them
    """
    Target = apps.get_model('mi', 'Target')
    HVCGroup = apps.get_model('mi', 'HVCGroup')
    hvc_groups_corrections = {
        "E012": "Advanced Manufacturing - Marine",
        "E022": "Advanced Manufacturing - Marine",
        "E148": "Advanced Manufacturing - Marine",
    }
    for hvc, group in hvc_groups_corrections.items():
        target = Target.objects.get(campaign_id=hvc)
        target.hvc_group = HVCGroup.objects.get(name=group)
        target.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0024_auto_20170120_1649'),
    ]

    operations = [
        migrations.RunPython(correct_targets),
    ]
