# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-22 11:49
from __future__ import unicode_literals

from django.db import migrations


def do_thing(apps, schema_editor):
    Test = apps.get_model('mi', 'Test')
    for x in range(10000):
        Test(test=True).save()


class Migration(migrations.Migration):

    dependencies = [
        ('mi', '0026_auto_20170222_1148'),
    ]

    operations = [
        migrations.RunPython(do_thing),
    ]
