SECTOR_TEAMS = {
    1: 'Financial & Professional Services',
    2: 'Education',
    3: 'Technology',
    4: 'Food & Drink',
    5: 'Aerospace',
    6: 'Infrastructure',
    7: 'Energy',
    8: 'Life Sciences',
    9: 'Advanced Manufacturing',
    10: 'Consumer & Creative',
    11: 'Automotive',
    12: 'Healthcare',
    13: 'Bio-economy',
    14: 'Defence & Security'
}

HVC_GROUPS = {
    1: 'Advanced Manufacturing',
    2: 'Advanced Manufacturing - Marine',
    3: 'Aerospace',
    4: 'Automotive',
    5: 'Bio-economy - Agritech',
    6: 'Bio-economy - Chemicals',
    7: 'Consumer Goods & Retail',
    8: 'Creative Industries',
    9: 'Defence',
    10: 'Digital Economy',
    11: 'Education',
    12: 'Energy - Nuclear',
    13: 'Energy - Offshore Wind',
    14: 'Energy - Oil & Gas',
    15: 'Energy - Renewables',
    16: 'Financial Services',
    17: 'Food & Drink',
    18: 'Healthcare',
    19: 'Infrastructure - Aid Funded Business',
    20: 'Infrastructure - Airports',
    21: 'Infrastructure - Construction',
    22: 'Infrastructure - Mining',
    23: 'Infrastructure - Rail',
    24: 'Infrastructure - Water',
    25: 'Life Sciences',
    26: 'Professional Services',
    27: 'Sports Economy',
    28: 'Strategic Campaigns'
}

HVC_GROUP_SECTOR_TEAM_MAP = {
    "Advanced Manufacturing": "Advanced Manufacturing",
    "Advanced Manufacturing - Marine": "Advanced Manufacturing",
    "Aerospace": "Aerospace",
    "Automotive": "Automotive",
    "Bio-economy - Agritech": "Bio-economy",
    "Bio-economy - Chemicals": "Bio-economy",
    "Consumer Goods & Retail": "Consumer & Creative",
    "Creative Industries": "Consumer & Creative",
    "Defence": "Defence & Security",
    "Digital Economy": "Technology",
    "Education": "Education",
    "Energy - Nuclear": "Energy",
    "Energy - Offshore Wind": "Energy",
    "Energy - Oil & Gas": "Energy",
    "Energy - Renewables": "Energy",
    "Financial Services": "Financial & Professional Services",
    "Food & Drink": "Food & Drink",
    "Healthcare": "Healthcare",
    "Infrastructure - Aid Funded Business": "Infrastructure",
    "Infrastructure - Airports": "Infrastructure",
    "Infrastructure - Construction": "Infrastructure",
    "Infrastructure - Mining": "Infrastructure",
    "Infrastructure - Rail": "Infrastructure",
    "Infrastructure - Water": "Infrastructure",
    "Life Sciences": "Life Sciences",
    "Professional Services": "Financial & Professional Services",
    "Sports Economy": "Consumer & Creative",
    "Strategic Campaigns": "Defence & Security"
}
