# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0021_auto_20160815_1409'),
        ('wins', '0018_auto_20160818_1518'),
    ]

    operations = [
    ]
