# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0025_auto_20160923_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
