# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0026_auto_20160930_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='hvc',
            field=models.CharField(blank=True, choices=[], max_length=6, null=True, verbose_name='HVC code, if applicable'),
        ),
    ]
