# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0030_auto_20170113_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='audit',
            field=models.TextField(null=True),
        ),
    ]
