# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-28 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wins', '0031_win_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HVC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
